version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    # Improve MySQL performance
    command:
      - --key_buffer_size=128M
      - --query_cache_size=128M
      - --query_cache_limit=8M
      - --tmp_table_size=256M
      - --max_heap_table_size=256M
      - --innodb_buffer_pool_size=1G
      - --innodb_read_io_threads=8
      - --innodb_write_io_threads=8
      - --innodb_flush_log_at_trx_commit=2
      - --max_connections=500
    # Resource allocation
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  wordpress:
    build: .  # Use the Dockerfile in the current directory
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:80"
    volumes:
      # Use a named volume for wp-content for better performance
      - wp_content_data:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      # PHP performance improvements
      PHP_MEMORY_LIMIT: 1024M
      PHP_MAX_EXECUTION_TIME: 600
      PHP_UPLOAD_MAX_FILESIZE: 128M
      PHP_POST_MAX_SIZE: 128M
    # Grant proper permissions on startup
    user: "root"
    # Resource allocation
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

volumes:
  db_data:
  wp_content_data: # Define the named volume for wp-content